<?php

namespace abei2017\wx\mp\qrcode;

use abei2017\wx\core\Driver;
use abei2017\wx\core\AccessToken;
use yii\helpers\Json;
use yii\httpclient\Client;

class Qrcode extends Driver {

    private $accessToken;

    //  生成临时二维码
    const API_QRCODE_URL = 'https://api.weixin.qq.com/cgi-bin/qrcode/create?access_token=';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->accessToken = (new AccessToken(['conf'=>$this->conf,'httpClient'=>$this->httpClient]))->getToken();
    }

    /**
     * 生成临时二维码
     *
     * @param $seconds integer 过期秒数
     * @param $val integer 二维码的值
     * @author abei<abei@nai8.me>
     * @return array
     */
    public function intTemp($seconds = 2592000,$val){
        return $this->temp('QR_SCENE',$seconds,['scene_id'=>$val]);
    }

    public function strTemp($seconds = 2592000,$val){
        return $this->temp('QR_STR_SCENE',$seconds,['scene_str'=>$val]);
    }

    private function temp($action = 'QR_SCENE', $seconds = 2592000, $scene = ['scene_id'=>0]){

        $params = array_merge(['expire_seconds'=>$seconds,'action_name'=>$action,'action_info'=>['scene'=>$scene]]);
        $response = $this->httpClient->createRequest()
            ->setUrl(Qrcode::API_QRCODE_URL.$this->accessToken)
            ->setMethod('post')
            ->setFormat(Client::FORMAT_JSON)
            ->setData($params)->send();

        $response->setFormat(Client::FORMAT_JSON);
        return $response->getData();
    }

    /**
     *
     */
    public function intForver($val){
        return $this->forver('QR_LIMIT_SCENE',['scene_id'=>$val]);
    }

    public function strForver($val){
        return $this->forver('QR_LIMIT_STR_SCENE',['scene_str'=>$val]);
    }

    private function forver($action = 'QR_LIMIT_SCENE', $scene = ['scene_id'=>0]){

        $params = array_merge(['action_name'=>$action,'action_info'=>['scene'=>$scene]]);
        $response = $this->httpClient->createRequest()
            ->setUrl(Qrcode::API_QRCODE_URL.$this->accessToken)
            ->setMethod('post')
            ->setFormat(Client::FORMAT_JSON)
            ->setData($params)->send();

        $response->setFormat(Client::FORMAT_JSON);
        return $response->getData();
    }
}